package esei.ssi.eperegrino.common;

public final class NombresBloques {
	public static final String TITULO_BLOQUE_DATOS_PEREGRINO = "DATOS PEREGRINO";
	public static final String TITULO_BLOQUE_CLAVE_DATOS_PEREGRINO = "CLAVE DATOS PEREGRINO";
	public static final String TITULO_BLOQUE_RESUMEN_DATOS_PEREGRINO_ENCRIPTADOS = "RESUMEN DATOS PEREGRINO ENCRIPTADOS";

	public static final String TITULO_BLOQUE_DATOS_SELLO_ALBERGUE_PARCIAL = "DATOS SELLO ALBERGUE ";
	public static final String TITULO_BLOQUE_DATOS_SELLO_ALBERGUE = "DATOS SELLO ALBERGUE {ID}";
	public static final String TITULO_BLOQUE_CLAVE_SELLO_ALBERGUE_PARCIAL = "CLAVE DATOS SELLO ALBERGUE ";
	public static final String TITULO_BLOQUE_CLAVE_SELLO_ALBERGUE = "CLAVE DATOS SELLO ALBERGUE {ID}";
	public static final String TITULO_BLOQUE_RESUMEN_SELLO_ALBERGUE_ENCRIPTADOS_PARCIAL = "RESUMEN DATOS SELLO ALBERGUE ";
	public static final String TITULO_BLOQUE_RESUMEN_SELLO_ALBERGUE_ENCRIPTADOS = "RESUMEN DATOS SELLO ALBERGUE {ID}";

	private NombresBloques() {
		// No permitir instanciar esta clase
	}
}
